### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by Ricardokevins** [CarolLi/fairseqBart#1]
您是否成功的复现了结果，可以公开一下处理后的CNNDM数据集吗，因为我这里一直复现的有一些问题。。
感谢您的回复和帮助~

**Comment by CarolLi** [comment]
是复现了，但是数据在学校的服务器，但我已经毕业了获取不了。你那边大概是什么问题可以说一下吗？

**Comment by Ricardokevins** [comment]
> 是复现了，但是数据在学校的服务器，但我已经毕业了获取不了。你那边大概是什么问题可以说一下吗？

昂，感谢，我找不到合适的数据处理脚本（训练都是Fairseq提供的脚本和代码，应该是数据问题），从官方渠道获取的数据是被写成了 *.bin的形式，Fairseq则是需要 *.source *.target的形态，可能这里的转化脚本有点问题。所以过来问问有没有处理好的数据。没有就算了哈哈哈，我再看看。谢谢了

**Comment by CarolLi** [comment]
> > 是复现了，但是数据在学校的服务器，但我已经毕业了获取不了。你那边大概是什么问题可以说一下吗？
> 
> 昂，感谢，我找不到合适的数据处理脚本（训练都是Fairseq提供的脚本和代码，应该是数据问题），从官方渠道获取的数据是被写成了 *.bin的形式，Fairseq则是需要 *.source *.target的形态，可能这里的转化脚本有点问题。所以过来问问有没有处理好的数据。没有就算了哈哈哈，我再看看。谢谢了

你说的数据指的是bart.large.cnn.tar.gz数据集吗？我这边README.md准备了数据集的下载链接，里面好像就是直接是*.source *.target的文件数据。
